version: '3.9'
services:
  api:
    build: ../server
    ports:
      - "3001:3001"
    env_file:
      - ../server/.env

  web:
    image: nginx:alpine
    volumes:
      - ../:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
